museum/collection/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^upload/$', 'museum.collection.views.upload', name='upload'),
    url(r'^query/$', 'museum.collection.views.query', name='query'),
    url(r'^group/$', 'museum.collection.views.group', name='group'),
    url(r'^make_group/$', 'museum.collection.views.make_group', 
    	name='make_group'),
    url(r'^edit/$', 'museum.collection.views.edit', name='edit'),
    url(r'^redirect/$', 'museum.collection.views.query_select',
    	name='query_redirect'),
)

museum/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView
from django.contrib import admin

admin.autodiscover()


urlpatterns = patterns('',
	# make sure everyone is logged in.
	(r'^$', RedirectView.as_view(url='lobby/')),
	url(r'login/$', 'django.contrib.auth.views.login', 
		{'template_name': 'login.html'}, name='login'),
	# everyone enters through the lobby.
	url(r'^lobby/', include('museum.lobby.urls')),
	# default permission is to view exhibits
	url(r'^exhibit/', include('museum.exhibit.urls')),
	# some users can curate collections
	url(r'^collection/', include('museum.collection.urls')),
	# log out users.

	url(r'logged_out/$', 'django.contrib.auth.views.logout', 
		{'template_name': 'logged_out.html'}, name='logged_out'),

	# set up admin:
	url(r'^admin/', include(admin.site.urls)),
)# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

museum/collection/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.forms import ModelForm

import os, datetime
from museum import settings

fs = FileSystemStorage(location=settings.PRIVATE_MEDIA_ROOT, 
        base_url=settings.PRIVATE_MEDIA_URL)
        

def uploadmodel_file_upload_to(instance, filename):
        return (instance.date_recorded + '/' + 
        	instance.animalID + '/' + filename)


SPECIES = (
    ('m_fasciularis', 'Macaca fasciularis'),
    ('m_nemestrina', 'Macaca nemestrina'),
    ('m_mulatta', 'Macaca mulatta'),
    ('m_sinica', 'Macaca sinica'),
    ('m_nemestrina', 'Macaca nemestrina'),
    ('m_sylvanus', 'Macaca sylvanus'),
    ('h_sapiens', 'Homo sapiens'),
    ('baboon', 'baboon'),
    ('S_sciureus', 'Saimiri sciureus'), 
    ('unknown', 'unknown'),
    )

SEX = (('male', 'male'), ('female', 'female'), ('unknown', 'unknown'), )

EYE = (('right', 'right'), ('left', 'left'), ('unknown', 'unknown'), )

CELLCLASS = (
    ('ganglion', 'ganglion cell'),
    ('amacrine', 'amacrine cell'),
    ('bipolar', 'bipolar cell'),
    ('horizontal', 'horizontal cell'),
    ('photoreceptor', 'photoreceptor'), )

STIMCLASS = (
    ('visual', 'visual stimulus',),
    ('current', 'current injection'),
    )

QUALITY = (
    ('excellent', 'excellent'),
    ('good', 'good'),
    ('average', 'average'),
    ('poor', 'poor'), )

CELLTYPE = (
    ('m_ganglion', 'midget ganglion'),
    ('p_ganglion', 'parasol ganglion'),
    ('s_bistrat', 'small bistratified'),
    ('l_bistrat', 'large bistratified'),
    ('b_thorny', 'broad thorny'),
    ('spider', 'spider amacrine'),
    ('starburst', 'starburst amacrine'),
    ('m_bipolar', 'midget bipolar'),
    ('d_bipolar', 'diffuse bipolar'),
    ('h1', 'H1 horizontal'),
    ('h2', 'H2 horizontal'),
    ('L_cone', 'L cone'),
    ('M_cone', 'M cone'),
    ('S_cone', 'S cone'),
    ('rod', 'rod'), )


class Epoch(models.Model):
    '''
    '''
    user = models.ForeignKey(User)
    date_added = models.DateField(default=datetime.date.today)
    date_recorded = models.DateField()

    # Experiment info
    animalID = models.CharField(max_length=15)
    species = models.CharField(max_length=50,
                                choices=SPECIES,
                                default='m_fasciularis')
    sex = models.CharField(max_length=7,
                                choices=SEX,
                                default='male')
    age = models.IntegerField()
    weight = models.IntegerField()
    eye = models.CharField(max_length=7,
                            choices=EYE,
                            default='male')

    # Cell info
    mountNumber = models.CharField(max_length=50)
    ampNumber = models.CharField(max_length=3)
    cellID = models.CharField(max_length=15)
    cellClass = models.CharField(max_length=13,
                                choices=CELLCLASS,
                                default='ganglion')
    cellType = models.CharField(max_length=20,
                                choices=CELLTYPE,
                                default='parasol')
    quality = models.CharField(max_length=13,
                                choices=QUALITY,
                                default='average')

    # Stimulus info
    stimulusClass = models.CharField(max_length=13,
                                choices=STIMCLASS,
                                default='visual')

    epochs = models.CharField(max_length=5000)
    #docfile = models.FileField(upload_to='museum/tmp/temp.mat', storage=fs)


class EpochForm(ModelForm):
    class Meta:
        model = Epoch
        fields = ['date_recorded', 'animalID', 'species',
        'sex', 'age', 'weight', 'eye', 'mountNumber',
        'ampNumber', 'cellID', 'cellClass', 'cellType',
        'quality', 'stimulusClass']


class QueryForm(ModelForm):
    class Meta:
        model = Epoch
        fields = ['species', 'cellClass', 'cellType', 'stimulusClass']


class EpochData(models.Model):

    binRate = models.FloatField()
    numSegments = models.FloatField()
    si = models.FloatField()
    clockstep = models.FloatField()
    sampleInterval = models.FloatField()
    sampleRate = models.FloatField()
    
    ampGain = models.FloatField()
    frameRate = models.FloatField()
    preSamples = models.FloatField()
    postSamples = models.FloatField()
    stimSamples = models.FloatField()
    time = models.FloatField()
    epochsize = models.FloatField()
    # string fields
    ampMode = models.CharField(max_length=100, default='none')
    recordingMode = models.CharField(max_length=100, default='none')
    outputClass = models.CharField(max_length=100, default='none')
    stimulusType = models.CharField(max_length=100, default='none')
    epochComment = models.CharField(max_length=1000, default='none')
    epoch = models.ForeignKey(Epoch)


class EpochParams(models.Model):

    Xpos = models.FloatField()
    Ypos = models.FloatField()
    diameter = models.FloatField()
    epochNumber = models.FloatField()
    flipInterval = models.FloatField()
    integratedIntensity = models.FloatField()
    intensity = models.FloatField()
    intensity_raw = models.FloatField()
    rand_behavior = models.FloatField()
    repositoryVersion = models.FloatField()
    screenX = models.FloatField()
    screenY = models.FloatField()
    sequential = models.FloatField()
    spatial_meanLevel = models.FloatField()
    spatial_postpts = models.FloatField()
    spatial_prepts = models.FloatField()
    windowPtr = models.FloatField()
    # string fields
    stimClass = models.CharField(max_length=100)
    colorGammaTable = models.CharField(max_length=10000)
    MatlabCodeDir = models.CharField(max_length=200)
    epoch = models.ForeignKey(Epoch)


class EpochGroup(models.Model):
    
    user = models.ForeignKey(User)
    date_added = models.DateField(default=datetime.date.today)
    date_modified = models.DateField(default=datetime.date.today)
    name = models.CharField(max_length=100)
    cells = models.ManyToManyField(Epoch)

museum/collection/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
import os, datetime
from array import array

import museum.collection.mat_upload as mat
from museum.collection.models import (Epoch, EpochData, EpochParams, 
    EpochForm, EpochGroup)
from museum.collection.forms import QueryForm
from museum.exhibit.views import get_directory_from_date
from museum import settings


UP_PATH = 'museum/storage/tmp/temp.mat'


@login_required
def make_group(request):
    '''
    '''
    if request.method == 'POST':
        user = request.user
        cellID = request.POST.getlist('cellID')
        group_name = request.POST.get('name')
        # make sure group doesn't already exist:
        try:
            obj = EpochGroup.objects.get(name=group_name)
            message = 'This cell already exists in the database. \
            Not imported.'
            return render_to_response(
                'success.html',
                {'user': str(request.user),
                'message': message,
                'link': 'group',
                'logged_in': logged_in, },
                context_instance=RequestContext(request)
            )   

        except EpochGroup.DoesNotExist:

            E_Group = EpochGroup(name=group_name)
            E_Group.user = user
            E_Group.save()
            for cell in cellID:
                epoch = Epoch.objects.get(cellID=cell)
                E_Group.date_modified = datetime.date.today()
                E_Group.cells.add(epoch)

            E_Group.save()
            if 'create' in request.POST:
                message = 'Successfully created Epoch Group.'
                return render_to_response(
                    'success.html',
                    {'message': message, 
                    'link': 'group',
                    'logged_in': True, },
                    context_instance=RequestContext(request)
                )  

@login_required
def group(request):
    '''
    '''
    logged_in = True
    if request.method == 'GET':
        form = QueryForm()
        return render_to_response(
            'group.html',
            {'form': form,
            'results': None,
             'user': str(request.user),
            'logged_in': logged_in, },
            context_instance=RequestContext(request)
        )    
    message = ''   
    if request.method == 'POST':

        form = QueryForm()

        species = request.POST.get('species')
        cellClass = request.POST.get('cellClass')
        cellType = request.POST.get('cellType')
        stimulusClass = request.POST.get('stimulusClass')
        stimulusType = request.POST.get('stimulusType')
        results = Epoch.objects.all()
        # filter results based on query
        if species != '' and species is not None:
            results = results.filter(species=species)
        if cellClass != '' and cellClass is not None:
            results = results.filter(cellClass=cellClass)
        if cellType != '' and cellType is not None:
            results = results.filter(cellType=cellType)
        if stimulusClass != '' and stimulusClass is not None:
            results = results.filter(stimulusClass=stimulusClass)
        if stimulusType != '' and stimulusType is not None:
            results = results.filter(stimulusClass=stimulusClass)

        if len(results) == 0:
            message = 'No results found, try broadening criteria'

        return render_to_response(
            'group.html',
            {'form': form,
            'message': message,
            'results': results, 
            'user': str(request.user),
            'logged_in': logged_in, },
            context_instance=RequestContext(request)
        )       

@login_required
def query(request):
    '''
    '''
    logged_in = True
    if request.method == 'GET':
        form = QueryForm()
        return render_to_response(
            'query.html',
            {'form': form,
            'results': None,
             'user': str(request.user),
            'logged_in': logged_in, },
            context_instance=RequestContext(request)
        )    
    message = ''   
    if request.method == 'POST':
        form = QueryForm()

        species = request.POST.get('species')
        cellClass = request.POST.get('cellClass')
        cellType = request.POST.get('cellType')
        stimulusClass = request.POST.get('stimulusClass')
        stimulusType = request.POST.get('stimulusType')
        results = Epoch.objects.all()
        # filter results based on query
        if species != '' and species is not None:
            results = results.filter(species=species)
        if cellClass != '' and cellClass is not None:
            results = results.filter(cellClass=cellClass)
        if cellType != '' and cellType is not None:
            results = results.filter(cellType=cellType)
        if stimulusClass != '' and stimulusClass is not None:
            results = results.filter(stimulusClass=stimulusClass)
        if stimulusType != '' and stimulusType is not None:
            results = results.filter(stimulusClass=stimulusClass)

        if len(results) == 0:
            message = 'No results found, try broadening criteria'

        return render_to_response(
            'query.html',
            {'form': form,
            'message': message,
            'results': results, 
            'user': str(request.user),
            'logged_in': logged_in, },
            context_instance=RequestContext(request)
        )       

@login_required
def query_select(request):
    '''
    '''
    logged_in = True
    if request.method == 'POST':
        cellID = request.POST.get('cellID')
        if 'delete' in request.POST:
            Epoch.objects.filter(
                cellID=cellID).delete()
            message = 'Successfully removed database entry.'
            return render_to_response(
                'success.html',
                {'message': message,
                'logged_in': logged_in,},
                context_instance=RequestContext(request)
            )  
        if 'view' in request.POST:
            
            date = get_date_from_cellID(cellID)
            location = date + cellID
            return redirect(reverse('museum.exhibit.views.viewer',
                kwargs={'location': location}))

        if 'edit' in request.POST:

            cell = Epoch.objects.get(cellID = cellID)       
            cell_form = EpochForm(instance=cell)

            return render_to_response('edit.html',
                {'cellID': cellID,
                'form': cell_form,
                'logged_in': logged_in, }, 
                context_instance=RequestContext(request))
   

@login_required
def edit(request):
    '''
    '''
    logged_in = True
    if request.POST:
        if 'cancel' in request.POST:
            message = 'No changes were made to the database.'
        if 'save' in request.POST:
            print request.POST
            cellID = request.POST.get('save')
            epoch = Epoch.objects.get(cellID = cellID)  
            form = EpochForm(request.POST, instance=epoch)
            _m = form.save(commit=False)
            # fill out remainder of Epoch form
            _m.user = request.user
            _m.date_added = datetime.date.today()
            _m.save()
            message = 'Changes were successfully saved to\
            the database.'

        return render_to_response('edit.html',
            {'message': message,
            'logged_in': logged_in, }, 
            context_instance=RequestContext(request))           


@login_required
def upload(request):
    '''
    '''
    logged_in = True
    if request.method == 'GET':

        form = EpochForm() # A empty, unbound form
        return render_to_response(
            'upload.html',
            {'form': form, 'user': str(request.user),
            'logged_in': logged_in, },
            context_instance=RequestContext(request)
        )            

    if request.method == 'POST':

        # get directory path of upload files:
        form = EpochForm(request.POST, request.FILES)
        # check to make sure that cellID doesn't already exist
        try:
            cellID = request.POST.get('cellID')
            obj = Epoch.objects.get(cellID=cellID)
            message = 'This cell already exists in the database. \
            Not imported.'
            return render_to_response(
                'upload.html',
                {'user': str(request.user),
                'message': message,
                'logged_in': logged_in, },
                context_instance=RequestContext(request)
            )                
        except Epoch.DoesNotExist:
            pass
        # check if form is valid
        if form.is_valid():
            _m = form.save(commit=False)
            # fill out remainder of Epoch form
            _m.user = request.user
            #_m.date_added = datetime.date.today()
            # save epochs in csv format
            epochs = []
            for fil in request.FILES.getlist('docfile'):
                epochs.append(str(fil) + ',')
            _m.epochs = epochs # get from name
            _m.save()
            for fil in request.FILES.getlist('docfile'):
                file_name = str(fil)[:-4]
                d = fil
                # upload to tmp dir
                handle_uploaded_file(d)
                # read in tmp file and open
                raw_data = mat.OpenMatlabData(UP_PATH)
                # process numpy array
                _dict = mat.ImportDataFromRiekeLab(raw_data)
                # handle any -1 in string category
                _dict = clean_strings(_dict)
                # save files to binary file
                save_binary_files(_dict, file_name, 
                    cellID)
                
                # epoch data

museum/collection/templates/edit.html
{% extends "base.html" %}

        
{% block content %}
{% load staticfiles %}
<link href="{% static 'collection/style/upload.css' %}" rel="stylesheet">

<div class="form-upload">
<!-- Upload form. Note enctype attribute! -->
<form action="{% url "edit" %}" method="post" enctype="multipart/form-data" class="form-submit">
        {% csrf_token %}
        {{ form.as_p }}
        <p>{{ form.non_field_errors }}</p>
        <p> {{ form.docfile.help_text }}</p>
        <p>
        {{ form.docfile.errors }}
        </p>
        {% if form %}
                <br>
               <button type="submit" name="cancel" value="True" class="cellBTN btn btn-lg">Cancel</button>
        	<button type="submit" name="save" value="{{ cellID }}" class="cellBTN btn-lg btn-primary btn2">Submit</button>
 
        {% else %}
        	<h2>{{ message }}</h2>
        	<a href="{% url "query" %}">Return to edit / querying.</a>
        {% endif %}

</form>
</div>

{% endblock %}

museum/collection/templates/group.html
{% extends "base.html" %}

        
{% block content %}
{% load staticfiles %}
<link href="{% static 'collection/style/query.css' %}" rel="stylesheet">

<h2 class="instructions">Select epochs</h2><br>
<div class="form-query">
<form action="{% url "group" %}" method="post" enctype="multipart/form-data" class="form-submit">
        {% csrf_token %}
        
        
        {{ form.as_p }}
        <p>{{ form.non_field_errors }}</p>
        <p> {{ form.docfile.help_text }}</p>
        <p>
        {{ form.docfile.errors }}
        </p>        

        <button type="submit" value="Upload" class="btn btn-lg btn-primary btn2">Query</button>
</form>
</div>
    {% if results %}
        <br>
        <br>
        <h2> Results </h2>
        <form action="{% url "make_group" %}" method="post" enctype="multipart/form-data" class="form-submit">
  
            {% csrf_token %}
        <label for="id_name">Name</label>
        <input type="text" id="name" name="name" value=""></input><br><br>
        <table >
		<tr>
        <th><input onchange="changeSelection()" type="checkbox" id="all_checkbox" name="all" value="all"></input></th>
        <th>date</th>
		<th>cell ID </th>
		<th>age</th>
		<th>quality </th>
		<th>species </th>
		<th>cell type </th>
		<th>stimulus class </th>
		</tr>
        
        {% for result in results %}
        	
            <tr><td><input class="ch" type="checkbox" name="cellID" value="{{ result.cellID }}"></input></td>
                <td>{{ result.date_recorded }}</td>
        		<td>{{ result.cellID }}</td>
        		<td>{{ result.age }}</td>
        		<td>{{ result.quality }}</td>
        		<td>{{ result.species }}</td>
        		<td>{{ result.cellType }}</td>
        		<td>{{ result.stimulusClass }}</td>
            
        	<tr>
                
        {% endfor %}

        </form>
       	</table>
        <br>
        <button type="submit" name="create" value="True" class="cellBTN btn btn-lg">Create</button>     
    {% endif %}
    <h2>{{ message }}</h2>

    <script language="javascript">
        function changeSelection(){
        value = document.getElementById("all_checkbox").checked
        var length = document.getElementsByClassName("ch").length;
        if(value == 1){
            for(var i = 0; i < length; i++) {
                document.getElementsByClassName("ch")[i].checked = true;
            };
        }
        else {
            for(var i = 0; i < length; i++) {
                document.getElementsByClassName("ch")[i].checked = false;
            };
        //document.getElementsByClassName("ch").options[0].selected = "";
        };
        };
    </script>

{% endblock %}

museum/collection/templates/query.html
{% extends "base.html" %}

        
{% block content %}
{% load staticfiles %}
<link href="{% static 'collection/style/query.css' %}" rel="stylesheet">

<h2 class="instructions">Select field values for query</h2><br>
<div class="form-query">
<form action="{% url "query" %}" method="post" enctype="multipart/form-data" class="form-submit">
        {% csrf_token %}

        {{ form.as_p }}
        <p>{{ form.non_field_errors }}</p>
        <p> {{ form.docfile.help_text }}</p>
        <p>
        {{ form.docfile.errors }}
        </p>        

        <button type="submit" value="Upload" class="btn btn-lg btn-primary btn2">Query</button>
</form>
</div>
    {% if results %}
        <br>
        <br>
        <h2> Results </h2>
        <form action="{% url "query_redirect" %}" method="post" enctype="multipart/form-data" class="form-submit">
            {% csrf_token %}
        <table >
		<tr>
        <th> </th>
        <th>date</th>
		<th>cell ID </th>
		<th>age</th>
		<th>quality </th>
		<th>species </th>
		<th>cell type </th>
		<th>stimulus class </th>
		</tr>
        
        {% for result in results %}
        	
            <tr><td><input type="radio" name="cellID" value="{{ result.cellID }}"></input></td>
                <td>{{ result.date_recorded }}</td>
        		<td>{{ result.cellID }}</td>
        		<td>{{ result.age }}</td>
        		<td>{{ result.quality }}</td>
        		<td>{{ result.species }}</td>
        		<td>{{ result.cellType }}</td>
        		<td>{{ result.stimulusClass }}</td>
            
        	<tr>
                
        {% endfor %}

        </form>
       	</table>
        <br>
        <button type="submit" name="view" value="True" class="cellBTN btn btn-lg">View</button>
        <button type="submit" name="edit" value="True" class="cellBTN btn btn-lg">Edit</button>        
        <button type="submit" name="delete" value="True" class="delBTN btn btn-lg">Delete</button>
    {% endif %}
    <h2>{{ message }}</h2>
{% endblock %}

museum/collection/templates/success.html
{% extends "base.html" %}

        
{% block content %}
{% load staticfiles %}
<link href="{% static 'collection/style/upload.css' %}" rel="stylesheet">

<div class="success-delete">

<h2>{{ message }}</h2>
{% if link == 'group' %}
	<a href="{% url "group" %}">Create another group.</a>
{% else %}
	<a href="{% url "query" %}">Return to query.</a>
{% endif %}

</div>

{% endblock %}

museum/collection/templates/upload.html
{% extends "base.html" %}

        
{% block content %}
{% load staticfiles %}
<link href="{% static 'collection/style/upload.css' %}" rel="stylesheet">

<div class="form-upload">
<!-- Upload form. Note enctype attribute! -->
<form action="{% url "upload" %}" method="post" enctype="multipart/form-data" class="form-submit">
        {% csrf_token %}
        {{ form.as_p }}
        <p>{{ form.non_field_errors }}</p>
        <p> {{ form.docfile.help_text }}</p>
        <p>
        {{ form.docfile.errors }}
        </p>
        {% if form %}
        	<input type="file" id="id_docfile" name="docfile" multiple>
        	<button type="submit" value="Upload" class="btn btn-lg btn-primary btn2">Import</button>
        {% else %}
        	<h2>{{ message }}</h2>
        	<a href="{% url "upload" %}">Import more files.</a>
        {% endif %}

</form>
</div>

{% endblock %}